<?php
return array(
	'ProgramDateWork'=>array(
		'name'=>'每日工作计划',
		'display'=>true,
		'child'=>array(
			'Index'=>array('name'=>'每日工作计划管理','display'=>true),
		),
	),
	'ProgramTask'=>array(
		'name'=>'绩效管理',
		'display'=>true,
		'child'=>array(
			'Index'=>array('name'=>'绩效管理页面','display'=>true),
			'Add'=>array('name'=>'增加任务','display'=>true),
			'Accept'=>array('name'=>'接受任务','display'=>false),
			'Edit'=>array('name'=>'编辑任务','display'=>false),
			'TimeoutCause'=>array('name'=>'完成任务时填写超时原因','display'=>false),
			'Finish'=>array('name'=>'完成任务','display'=>false),
			'Audit'=>array('name'=>'审核任务','display'=>false),			
		),
	),
	'ProgramProject'=>array(
		'name'=>'项目管理',
		'display'=>true,
		'child'=>array(
			'Index'=>array('name'=>'项目管理列表','display'=>true),
			'Add'=>array('name'=>'增加项目','display'=>true),
			'Edit'=>array('name'=>'编辑项目','display'=>false),
			'Del'=>array('name'=>'删除项目','display'=>false),
		),
	),
	'ProgramUser'=>array(
		'name'=>'用户管理',
		'display'=>true,
		'child'=>array(
			'Index'=>array('name'=>'用户列表','display'=>true),
			'Setup'=>array('name'=>'职位列表','display'=>true),
			'SetupAdd'=>array('name'=>'增加职位','display'=>false),
			'SetupEdit'=>array('name'=>'编辑职位','display'=>false),
			'SetupDel'=>array('name'=>'删除职位','display'=>false),
		),
	),
	'ProgramStats'=>array(
		'name'=>'考核统计',
		'display'=>true,
		'child'=>array(
			'Month'=>array('name'=>'月份统计','display'=>true),
			'Quarter'=>array('name'=>'季度统计','display'=>true),
			'MonthAssignMarks'=>array('name'=>'月份统计评分','display'=>false),
			'EditMonthMarks'=>array('name'=>'月份评分修改','display'=>false),
			'QuarterAssignMarks'=>array('name'=>'季度统计评分','display'=>false),
			'EditQuarterMarks'=>array('name'=>'季度评分修改','display'=>false),
		),
	),
);