<?php
return array(
	'ServiceAccept'=>array(
		'name'=>'服务受理率统计',
		'display'=>true,
		'child'=>array(
			'Order'=>array('name'=>'受理率统计','display'=>true,),
			'Satisfaction'=>array('name'=>'满意度统计','display'=>true),
			'Time'=>array('name'=>'工单处理时长统计','display'=>true),
		),
	),
	'StatsGmAudit'=>array(
		'name'=>'审核统计',
		'display'=>true,
		'child'=>array(
			'Index'=>array('name'=>'富人国审核统计','display'=>true),
		),
	),
	'StatsData'=>array(
		'name'=>'数据统计',
		'display'=>true,
		'child'=>array(
			'Data'=>array('name'=>'详细统计','display'=>true),
			'DataDetail'=>array('name'=>'详细统计详情_ajax','display'=>false),
			'LinkRelative'=>array('name'=>'环比统计','display'=>true),
		),
	),
	'StatsOperator'=>array(
		'name'=>'运营商统计',
		'display'=>true,
		'child'=>array(
			'Day'=>array('name'=>'运营商统计(按天)','display'=>true),
			'DayDetail'=>array('name'=>'运营商统计详细(按天)_ajax','display'=>false),
			'Hour'=>array('name'=>'运营商统计(按小时)','display'=>true),
			'HourDetail'=>array('name'=>'运营商统计详细(按小时)_ajax','display'=>false),
		),
	),
	'StatsFaq'=>array(
		'name'=>'FAQ统计',
		'display'=>true,
		'child'=>array(
			'Ev'=>array('name'=>'评价统计','display'=>true),
			'Ratio'=>array('name'=>'点击率统计','display'=>true),
		),
	),
);