<?php
return array(
	'SftxNotice'=>array(
		'name'=>'公告管理',
		'display'=>true,
		'child'=>array(
			'Index'=>array('name'=>'公告显示列表','display'=>true,),
			'Add'=>array('name'=>'增加公告','display'=>true),
			'Edit'=>array('name'=>'编辑公告','display'=>false),
			'Del'=>array('name'=>'删除公告','display'=>false),
			'AddMulti'=>array('name'=>'批量增加公告','display'=>true),
		),
	),
	'SftxUser'=>array(
		'name'=>'游戏用户管理',
		'display'=>true,
		'child'=>array(
			'Index'=>array('name'=>'用户管理','display'=>true),
			'UserGoldLog'=>array('name'=>'用户金币操作日志','display'=>true),
			'UserSilverLog'=>array('name'=>'用户银币操作日志','display'=>true),
			'UserFoodLog'=>array('name'=>'用户粮食操作日志','display'=>true),
			'ModifyName'=>array('name'=>'修改玩家的游戏名','display'=>true),
			//'GoodsLog'=>array('name'=>'物品日志','display'=>true),
		),
	),
	'SftxSysManage'=>array(
		'name'=>'GM管理工具',
		'display'=>true,
		'child'=>array(
			'SendMsg'=>array('name'=>'群发短信','display'=>true),
			'IpIndex'=>array('name'=>'封IP列表','display'=>true),
			'IpAdd'=>array('name'=>'增加封IP','display'=>false),
			'IpDel'=>array('name'=>'解除封IP','display'=>false),
	
			'ResUserIndex'=>array('name'=>'封号显示列表','display'=>true),
			'ResUserAdd'=>array('name'=>'增加封号','display'=>false),
			'ResUserDel'=>array('name'=>'解除封号','display'=>false),
			'ResUserCoerce'=>array('name'=>'强制解除封号','display'=>false),
	
			'TalkUserIndex'=>array('name'=>'禁言显示列表','display'=>true),
			'TalkUserAdd'=>array('name'=>'增加禁言','display'=>false),
			'TalkUserDel'=>array('name'=>'解除禁言','display'=>false),
			'TalkUserCoerce'=>array('name'=>'强制解除禁言','display'=>false),
			'Serverlist'=>array('name'=>'服务器管理','display'=>true,)
		),
	),
);