<?php
return array(
	'MasterTools'=>array(
		'name'=>'GM工具',
		'name_en'=>'GM Tools',
		'display'=>true,
		'child'=>array(
			'ServerState'=>array('name'=>'服务器在线状况','name_en'=>'Server Status','display'=>true),
			'OnLine'=>array('name'=>'在线用户','name_en'=>'Server Status','display'=>true),
			'PlayerLookup'=>array('name'=>'帐号查询','name_en'=>'Check Player','display'=>true),
			'PlayerRoleList'=>array('name'=>'角色查询','name_en'=>'Check Player Character','display'=>true),
			'PlayerRoleDelList'=>array('name'=>'已删除角色列表','name_en'=>'Check Player Character','display'=>true),
			'Organize'=>array('name'=>'帮会查询','name_en'=>'Check Guild','display'=>true),
			'PersonalInformation'=>array('name'=>'玩家个人信息查询','name_en'=>'Player Profile','display'=>true),
			'PlayerPartner'=>array('name'=>'玩家伙伴列表','name_en'=>'Player Partner List','display'=>true),
			'PlayerPartnerInfo'=>array('name'=>'玩家伙伴信息','name_en'=>'Player Partner Info','display'=>true),
			'UserCurrencyLog'=>array('name'=>'用戶資產使用日誌','name_en'=>'User Assets Log','display'=>true),
			'PlayerLog'=>array('name'=>'玩家操作日志','name_en'=>'Player Operation Log','display'=>true),
			'ItemLog'=>array('name'=>'道具日志','name_en'=>'Player Operation Log','display'=>true),
			'PlayerLogType'=>array('name'=>'玩家日志类型更新','name_en'=>'Refresh Player Log Type','display'=>false),
			'MailList'=>array('name'=>'邮件列表','name_en'=>'Mail List','display'=>true),
			'SendMail'=>array('name'=>'发送邮件','name_en'=>'Send Mail','display'=>true),
			'MailDel'=>array('name'=>'邮件删除','name_en'=>'Send Mail','display'=>false),
			'GameLogin'=>array('name'=>'登录玩家游戏','name_en'=>'Player Game Login','display'=>true),
			'Silence'=>array('name'=>'禁言管理','name_en'=>'Silence','display'=>true),
			'SilenceAdd'=>array('name'=>'添加禁言','name_en'=>'Add Silence','display'=>false),
			'SilenceDel'=>array('name'=>'删除禁言','name_en'=>'Revoke Silence','display'=>false),
			'LockAccount'=>array('name'=>'封号管理','name_en'=>'Banning','display'=>true),
			'LockAccountAdd'=>array('name'=>'添加封号','name_en'=>'Add Banning','display'=>false),
			'LockAccountDel'=>array('name'=>'删除封号','name_en'=>'Revoke Banning','display'=>false),
			'MultiLock'=>array('name'=>'多服封号/禁言','name_en'=>'Multi-server Banning/Silence','display'=>true),
			'LockIP'=>array('name'=>'IP封锁管理','name_en'=>'IP Blocking','display'=>true),
			'LockIPDone'=>array('name'=>'IP封锁操作','name_en'=>'IP Blocking Operation','display'=>false),
			'LockIPDel'=>array('name'=>'IP封锁操作','name_en'=>'IP Blocking Operation','display'=>false),
			'DelLockIP'=>array('name'=>'IP封锁操作','name_en'=>'IP Blocking Operation','display'=>false),
			'RechargeRecord'=>array('name'=>'充值记录','name_en'=>'Recharge Record','display'=>true),
			'Consumption'=>array('name'=>'消耗记录','name_en'=>'Recharge Record','display'=>true),
			'GetOperatorServer'=>array('name'=>'游戏运营商与服务器','name_en'=>'Publisher and Server','display'=>true),
			'BackpackSearch'=>array('name'=>'背包物品查询','name_en'=>'Check Bag','display'=>true),
			'Equipment'=>array('name'=>'装备查询','name_en'=>'Check Equipment','display'=>true),
			'EquipmentUpgrade'=>array('name'=>'装备升级申请','name_en'=>'Equipment Upgrade Application','display'=>false),
			'EquipmentDel'=>array('name'=>'装备删除申请','name_en'=>'Equipment Deletion Application','display'=>false),
			'SendUserPackage'=>array('name'=>'发放道具','name_en'=>'Gift Sending','display'=>true),
			'DelUserPackage'=>array('name'=>'删除道具','name_en'=>'Gift Del','display'=>true),
			'Item'=>array('name'=>'道具更新','name_en'=>'Refresh Item','display'=>false),
			'ItemDel'=>array('name'=>'道具删除','name_en'=>'Delete Item','display'=>false),
			'ApplyCard'=>array('name'=>'道具卡申请','name_en'=>'Apply Card','display'=>true),
			'ApplyIngot'=>array('name'=>'元宝申请','name_en'=>'Apply Ingot','display'=>true),
			'ItemCard'=>array('name'=>'礼包管理','name_en'=>'Gift Card No. Management','display'=>true),
			'ItemCard2'=>array('name'=>'客服礼包卡号管理','name_en'=>'CS Gift Card No. Management','display'=>true),
			'ItemCardApply'=>array('name'=>'道具卡申请','name_en'=>'Item Card Application','display'=>false),
			'ItemCardApply2'=>array('name'=>'道具卡申请','name_en'=>'Item Card Application','display'=>false),
			'ItemCardAppendApply'=>array('name'=>'追加道具卡申请','name_en'=>'Additional Item Card Application','display'=>false),
			'ItemCardQuery'=>array('name'=>'卡号查询','name_en'=>'Check Card No.','display'=>false),
			'ItemCardShowBatch'=>array('name'=>'查询礼包批次','name_en'=>'Check Gift Batch','display'=>false),
			'ItemCardList'=>array('name'=>'卡号列表','name_en'=>'Card No. List','display'=>false),
			'ItemCardDownLoad'=>array('name'=>'卡号下载','name_en'=>'Card No. Download','display'=>false),
			'PropertySend'=>array('name'=>'道具发放/扣除','name_en'=>'Item Sending/Deduction','display'=>true),
			'ItemDel'=>array('name'=>'道具删除','name_en'=>'Delete Item','display'=>false),
			'ItemPackageEdit'=>array('name'=>'礼包编辑','name_en'=>'Gift Editing','display'=>false),
			'PointDel'=>array('name'=>'点数扣除','name_en'=>'Amount Deduction','display'=>true),
			'OrderDetail'=>array('name'=>'Q币消费查询','name_en'=>'Check Q Coin Expense','display'=>true),
			'ConsumptionDetail'=>array('name'=>'消费查询','name_en'=>'Consumption Detail','display'=>true),
			'SetVIP'=>array('name'=>'玩家VIP设置','name_en'=>'VIP Player Setting','display'=>true),
			'UserLoginLog'=>array('name'=>'玩家登录情况','name_en'=>'User Login Log','display'=>true),
			'PlayerValueUpdate'=>array('name'=>'修改玩家数值','name_en'=>'VIP Player Setting','display'=>true),
			'Define'=>array('name'=>'常量、枚举、定义','name_en'=>'VIP Player Setting','display'=>false),
			'TaskManage'=>array('name'=>'任务管理','name_en'=>'Task Manage','display'=>true),
			'ClearCopyNum'=>array('name'=>'调整副本次数','name_en'=>'Clear CopyNum','display'=>true),
			'EditBoneLvel'=>array('name'=>'调根骨等级','name_en'=>'EditBoneLvel','display'=>true),
			'EditMountAndPet'=>array('name'=>'查询修改坐骑/宠物信息','name_en'=>'EditMountAndPet','display'=>true),
			'TitleOrGag'=>array('name'=>'封号禁言管理','name_en'=>'Title And Gag','display'=>true),
			'CopyPlayer'=>array('name'=>'复制玩家','name_en'=>'EditMountAndPet','display'=>true),
			'PlayerRegName'=>array('name'=>'角色注册名','name_en'=>'EditMountAndPet','display'=>true),
			'Log'=>array('name'=>'日志','name_en'=>'EditMountAndPet','display'=>true),
			'LogType'=>array('name'=>'日志类型配置','name_en'=>'EditMountAndPet','display'=>true),
			'PlayerInfoSale'=>array('name'=>'角色摊位查询','name_en'=>'PlayerInfoSale','display'=>true),
			'TradeManage'=>array('name'=>'交易管理','name_en'=>'TradeManage','display'=>true),
),
),
	'OperatorTools'=>array(
		'name'=>'运营工具',
		'name_en'=>'Operation Tools',
		'display'=>true,
		'child'=>array(
			'PowerAccount'=>array('name'=>'账号白名单','name_en'=>'','display'=>true),
			'PowerIP'=>array('name'=>'IP白名单','name_en'=>'','display'=>true),
			'WebList'=>array('name'=>'Web列表','name_en'=>'','display'=>true),
			'WebAdd'=>array('name'=>'Web添加','name_en'=>'','display'=>false),
			'DipList'=>array('name'=>'Dip列表','name_en'=>'','display'=>true),
			'PayAdd'=>array('name'=>'Pay添加','name_en'=>'','display'=>false),
			'PayList'=>array('name'=>'Pay列表','name_en'=>'','display'=>true),
			'DipAdd'=>array('name'=>'Dip添加','name_en'=>'','display'=>false),
			'ActivitiesConfiguration'=>array('name'=>'活动面板配置','name_en'=>'','display'=>true),
			'ActivitiesConfigurationAdd'=>array('name'=>'活动面板配置添加','name_en'=>'','display'=>false),
			'ActivitiesConfigurationDel'=>array('name'=>'活动面板配置删除','name_en'=>'','display'=>false),
			'ActivitiesConfigurationSync'=>array('name'=>'活动面板配置同步','name_en'=>'','display'=>true),
			'SendEmailMultiserver'=>array('name'=>'多服发送邮件','name_en'=>'','display'=>true),
			'SendGoodsMultiserver'=>array('name'=>'多服发送物品','name_en'=>'','display'=>true),
			'ServicerMaintain'=>array('name'=>'服务器维护状态','name_en'=>'','display'=>true),
			'ServicerMaintainSync'=>array('name'=>'服务器维护状态修改','name_en'=>'','display'=>false),
			'EventStoryList'=>array('name'=>'说说故事列表','name_en'=>'','display'=>true),
			'EventStoryAdd'=>array('name'=>'说说故事添加','name_en'=>'','display'=>false),
			'EventStoryDel'=>array('name'=>'说说故事删除','name_en'=>'','display'=>false),
			'ActivitiesList'=>array('name'=>'活动列表','name_en'=>'','display'=>true),
			'ActivitiesAdd'=>array('name'=>'活动添加','name_en'=>'','display'=>false),
			'ActivitiesDel'=>array('name'=>'活动删除','name_en'=>'','display'=>false),
			'ActivitiesEdit'=>array('name'=>'活动修改','name_en'=>'','display'=>false),
			'ShopProduce'=>array('name'=>'商城商品','name_en'=>'','display'=>true),
			'ShopProduceEdit'=>array('name'=>'修改商品','name_en'=>'','display'=>false),
			'QShopProduce'=>array('name'=>'Q币商城商品','name_en'=>'','display'=>true),
			'AddShopProduce'=>array('name'=>'商城商品添加','name_en'=>'','display'=>false),
			'AddQShopProduce'=>array('name'=>'Q币商城商品添加','name_en'=>'','display'=>false),
			'DelShopProduce'=>array('name'=>'商城商品删除','name_en'=>'','display'=>false),
			'DelQShopProduce'=>array('name'=>'Q币商城商品删除','name_en'=>'','display'=>false),
			'BadWord'=>array('name'=>'敏感字过滤','name_en'=>'Sensitive Words','display'=>true),
			'Notice'=>array('name'=>'公告','name_en'=>'Announcement','display'=>true),
			'AllNotice'=>array('name'=>'多服公告管理','name_en'=>'Multi-server Announcement Management','display'=>true),
			'AllNoticeAdd'=>array('name'=>'多服公告发送','name_en'=>'Multi-server Announcement Adding','display'=>true),
			'AllNoticeDel'=>array('name'=>'多服公告删除','name_en'=>'Multi-server Announcement Del','display'=>true),
			'NoticeAdd'=>array('name'=>'添加公告','name_en'=>'Add Announcement','display'=>false),
			'NoticeDel'=>array('name'=>'删除公告','name_en'=>'Delete Announcement','display'=>false),
			'NoticeEdit'=>array('name'=>'编辑公告','name_en'=>'Edit Announcement','display'=>false),
            'NoticeSync'=>array('name'=>'公告多服同步','name_en'=>'Edit Announcement','display'=>true),
			'ItemCardSync'=>array('name'=>'礼包多服同步','name_en'=>'Edit Announcement','display'=>true),
			'ActivitiesSync'=>array('name'=>'活动多服同步','name_en'=>'Edit Announcement','display'=>true),
			'ShopProduceSync'=>array('name'=>'商品多服同步','name_en'=>'Edit Announcement','display'=>true),
			'BossAdd'=>array('name'=>'添加BOss','name_en'=>'Add Announcement','display'=>false),
			'BossDel'=>array('name'=>'删除boss','name_en'=>'Delete Announcement','display'=>false),
			'BossList'=>array('name'=>'Boss列表','name_en'=>'Edit Announcement','display'=>true),
			'OpenTime'=>array('name'=>'开服时间查询','name_en'=>'Edit Announcement','display'=>true),

			'ServerManagement'=>array('name'=>'服务器管理','name_en'=>'Server Management','display'=>true),

			'RewardTriggerList'=>array('name'=>'奖励触发列表','name_en'=>'Reward trigger list','display'=>true),
			'RewardTriggerDel'=>array('name'=>'删除奖励触发','name_en'=>'Del Reward trigger','display'=>false),
			'RewardTriggerDels'=>array('name'=>'多服删除奖励触发','name_en'=>'Dels Reward trigger','display'=>true),
			'RewardTriggerAdd'=>array('name'=>'添加奖励触发','name_en'=>'Reward trigger list','display'=>true),
			'ActivationTypeAdd'=>array('name'=>'添加激活码类型','name_en'=>'Add Activation code type','display'=>true),
			'ActivationCodeAdd'=>array('name'=>'添加激活码','name_en'=>'Add Activation code','display'=>true),
			'ActivationCodeList'=>array('name'=>'激活码列表','name_en'=>'Add Activation code list','display'=>true),
			'ActivationTypeList'=>array('name'=>'激活码类型列表','name_en'=>'Add Activation code type list','display'=>true),
			'Recharge'=>array('name'=>'充值','name_en'=>'Recharge','display'=>true),
			'SysLog'=>array('name'=>'后台操作日志','name_en'=>'SysLog','display'=>true),
			'MallLogList'=>array('name'=>'商城消费日志','name_en'=>'Mall Log List','display'=>true),
			'FunOnOrOff'=>array('name'=>'功能开关','name_en'=>'function on/off','display'=>true),
			'ExcelImport'=>array('name'=>'Excel生成本地缓存','name_en'=>'Excel Import','display'=>true),
			'ServerOnOrOff'=>array('name'=>'开服停服','name_en'=>'server on/off','display'=>true),
			'AddPlayerAsGM'=>array('name'=>'添加GM','name_en'=>'Add Player As GM','display'=>true),
			'GMList'=>array('name'=>'GM帐号列表','name_en'=>'Get Ingot','display'=>true),
			'Patch'=>array('name'=>'补丁','name_en'=>'Patch','display'=>true),
			'GetIngotType'=>array('name'=>'金币流向类型','name_en'=>'Get Ingot Type','display'=>false),
			'GetIngot'=>array('name'=>'金币流向','name_en'=>'Get Ingot','display'=>true),
			'AddPlayerPay'=>array('name'=>'MVP金币','name_en'=>'add Player Pay','display'=>true),
			'ItemCardMotion'=>array('name'=>'礼包管理(运营用)','name_en'=>'Gift Card No. Management','display'=>true),
			'ItemCardApplyMotion'=>array('name'=>'道具卡申请(运营用)','name_en'=>'Item Card Application','display'=>false),

),
),
);